### ISSUE TITLE
transcoding_hd

### ISSUE THREAD

**Issue by marksjr** [m1k1o/hls-restream#10]
which command to activate transcoding_hd?

       test    http://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8 transcoding_hd

**Comment by m1k1o** [comment]
Using docker:

```yaml
version: "3.4"
services:
  hls:
    build: "./"
    container_name: "hls"
    restart: "always"
    tmpfs:
      - "/var/www/html:mode=777,size=128M,uid=1000,gid=1000"
    ports:
      - "80:80"
    environment:
      PROFILE: transcoding_hd
      SOURCES: |
        test    http://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8
```

Without docker:
```bash
./profiles/transcoding_hd.sh test http://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8
```

Output will be in `/var/www/html/` as `test.m3u8`.

**Comment by marksjr** [comment]
thank you, very good, later I will connect in a PHP panel to improve usability

**Comment by marksjr** [comment]
can enable the transcode individually for each channel? or active only for all channels?

**Comment by m1k1o** [comment]
Only for all channels at start in one container. But you can have one channel per container with multiple containers and start  / stop on demand.

**Comment by marksjr** [comment]
do you have any example of multiple containers

    environment:
      PROFILE: transcoding_hd
      SOURCES: |
        test    http://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8
    environment:
      PROFILE: transcoding_hd
      SOURCES: |
        test2    http://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8

**Comment by m1k1o** [comment]
E.G.

```yaml
version: "3.4"
services:
  test:
    build: "./"
    container_name: "test"
    restart: "always"
    tmpfs:
      - "/var/www/html:mode=777,size=128M,uid=1000,gid=1000"
    ports:
      - "8080:80"
    environment:
      PROFILE: transcoding_hd
      SOURCES: test http://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8
  test2:
    build: "./"
    container_name: "test2"
    restart: "always"
    tmpfs:
      - "/var/www/html:mode=777,size=128M,uid=1000,gid=1000"
    ports:
      - "8081:80"
    environment:
      PROFILE: transcoding_hd
      SOURCES: test2 http://cph-p2p-msl.akamaized.net/hls/live/2000341/test2/master.m3u8
```

And then you have `test` on `127.0.0.1:8080/test.m3u8` and `test2` on `127.0.0.1:8081/test2.m3u8`.
